apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf-service
  namespace: audiobookshelf
spec:
  selector:
    app: audiobookshelf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32731
  type: NodePort
