apiVersion: v1
kind: PersistentVolume
metadata:
  name: vscode-config-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
  hostPath:
    path: /home/k8svolumes/vscode/config
