apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-config-pvc
  namespace: vscode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
