apiVersion: v1
kind: PersistentVolume
metadata:
  name: vscode-extensions-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
  hostPath:
    path: /home/k8svolumes/vscode/extensions ## Change to the desired path
    type: DirectoryOrCreate
