apiVersion: v1
data:
  PASSWORD: aTlwam9oZCEtWSFpSHU=
kind: Secret
metadata:
  creationTimestamp: "2025-05-17T22:53:27Z"
  name: vscode-password
  namespace: vscode
  resourceVersion: "1036972"
  uid: 4a31eb5b-42f5-404a-9b34-0adf33a481de
type: Opaque
