apiVersion: v1
kind: Secret
metadata:
  name: reactive-resume-database-secret
  namespace: reactive-resume
type: Opaque
data:
  # postgres (base64 encoded)
  POSTGRES_DB: cG9zdGdyZXM=
  # postgres (base64 encoded)  
  POSTGRES_USER: cG9zdGdyZXM=
  # postgres (base64 encoded) - Change this to a secure password
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # postgresql://postgres:postgres@reactive-resume-database:5432/postgres (base64 encoded)
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHJlYWN0aXZlLXJlc3VtZS1kYXRhYmFzZTo1NDMyL3Bvc3RncmVz