apiVersion: v1
kind: PersistentVolume
metadata:
  name: reactive-resume-database-pv
  namespace: reactive-resume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /home/k8svolumes/reactive-resume/mounted_volume/postgres_data
    type: DirectoryOrCreate