apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reactive-resume-database-pvc
  namespace: reactive-resume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: reactive-resume-database-pv