apiVersion: v1
kind: Service
metadata:
  name: reactive-resume-database
  namespace: reactive-resume
spec:
  selector:
    app: reactive-resume-database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP