apiVersion: v1
kind: Service
metadata:
  name: reactive-resume-chrome
  namespace: reactive-resume
spec:
  selector:
    app: reactive-resume-chrome
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP