apiVersion: v1
kind: Secret
metadata:
  name: reactive-resume-app-secret
  namespace: reactive-resume
type: Opaque
data:
  # access_token_secret (base64 encoded) - Change this to a secure secret
  ACCESS_TOKEN_SECRET: YWNjZXNzX3Rva2VuX3NlY3JldA==
  # refresh_token_secret (base64 encoded) - Change this to a secure secret
  REFRESH_TOKEN_SECRET: cmVmcmVzaF90b2tlbl9zZWNyZXQ=
  # chrome_token (base64 encoded) - Should match chrome service token
  CHROME_TOKEN: Y2hyb21lX3Rva2Vu
  # minioadmin (base64 encoded) - Should match minio credentials
  STORAGE_ACCESS_KEY: bWluaW9hZG1pbg==
  # minioadmin (base64 encoded) - Should match minio credentials
  STORAGE_SECRET_KEY: bWluaW9hZG1pbg==
  # -- Optional Secrets (add base64 encoded values when needed) --
  # CROWDIN_PERSONAL_TOKEN: ""
  # SMTP_URL: ""
  # GITHUB_CLIENT_ID: ""
  # GITHUB_CLIENT_SECRET: ""
  # GOOGLE_CLIENT_ID: ""
  # GOOGLE_CLIENT_SECRET: ""
  # OPENID_AUTHORIZATION_URL: ""
  # OPENID_CLIENT_ID: ""
  # OPENID_CLIENT_SECRET: ""
  # OPENID_ISSUER: ""
  # OPENID_TOKEN_URL: ""
  # OPENID_USER_INFO_URL: ""