apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-resume-app
  namespace: reactive-resume
  labels:
    app: reactive-resume-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactive-resume-app
  template:
    metadata:
      labels:
        app: reactive-resume-app
    spec:
      containers:
      - name: app
        image: amruthpillai/reactive-resume:latest
        ports:
        - containerPort: 3000
        env:
        # Environment Variables
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        # URLs - Update these with your actual server IP or domain
        - name: PUBLIC_URL
          value: "http://[your-server-ip]:3000"
        - name: STORAGE_URL
          value: "http://[your-server-ip]:30900/default"
        # Printer (Chrome)
        - name: CHROME_TOKEN
          valueFrom:
            secretKeyRef:
              name: reactive-resume-app-secret
              key: CHROME_TOKEN
        - name: CHROME_URL
          value: "ws://reactive-resume-chrome:3000"
        # Database (Postgres)
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: reactive-resume-database-secret
              key: DATABASE_URL
        # Auth
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: reactive-resume-app-secret
              key: ACCESS_TOKEN_SECRET
        - name: REFRESH_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: reactive-resume-app-secret
              key: REFRESH_TOKEN_SECRET
        # Emails
        - name: MAIL_FROM
          value: "noreply@localhost"
        # Storage (MinIO)
        - name: STORAGE_ENDPOINT
          value: "reactive-resume-minio"
        - name: STORAGE_PORT
          value: "9000"
        - name: STORAGE_REGION
          value: "us-east-1"
        - name: STORAGE_BUCKET
          value: "default"
        - name: STORAGE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: reactive-resume-app-secret
              key: STORAGE_ACCESS_KEY
        - name: STORAGE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: reactive-resume-app-secret
              key: STORAGE_SECRET_KEY
        - name: STORAGE_USE_SSL
          value: "false"
        - name: STORAGE_SKIP_BUCKET_CHECK
          value: "false"
        # -- Optional Features (uncomment and configure as needed) --
        # -- Crowdin (Optional) --
        # - name: CROWDIN_PROJECT_ID
        #   value: "your_crowdin_project_id"
        # - name: CROWDIN_PERSONAL_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: reactive-resume-app-secret
        #       key: CROWDIN_PERSONAL_TOKEN
        # -- Email (Optional) --
        # - name: DISABLE_SIGNUPS
        #   value: "false"
        # - name: DISABLE_EMAIL_AUTH
        #   value: "false"
        # - name: SMTP_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: reactive-resume-app-secret
        #       key: SMTP_URL
        # -- GitHub (Optional) --
        # - name: GITHUB_CLIENT_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: reactive-resume-app-secret
        #       key: GITHUB_CLIENT_ID
        # - name: GITHUB_CLIENT_SECRET
        #   valueFrom:
        #     secretKeyRef:
        #       name: reactive-resume-app-secret
        #       key: GITHUB_CLIENT_SECRET
        # - name: GITHUB_CALLBACK_URL
        #   value: "http://[your-server-ip]:30300/api/auth/github/callback"
        # -- Google (Optional) --
        # - name: GOOGLE_CLIENT_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: reactive-resume-app-secret
        #       key: GOOGLE_CLIENT_ID
        # - name: GOOGLE_CLIENT_SECRET
        #   valueFrom:
        #     secretKeyRef:
        #       name: reactive-resume-app-secret
        #       key: GOOGLE_CLIENT_SECRET
        # - name: GOOGLE_CALLBACK_URL
        #   value: "http://[your-server-ip]:30300/api/auth/google/callback"
        # -- OpenID (Optional) --
        # - name: VITE_OPENID_NAME
        #   value: "OpenID"
        # - name: OPENID_AUTHORIZATION_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: reactive-resume-app-secret
        #       key: OPENID_AUTHORIZATION_URL
        # - name: OPENID_CALLBACK_URL
        #   value: "http://[your-server-ip]:30300/api/auth/openid/callback"
        # - name: OPENID_CLIENT_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: reactive-resume-app-secret
        #       key: OPENID_CLIENT_ID
        # - name: OPENID_CLIENT_SECRET
        #   valueFrom:
        #     secretKeyRef:
        #       name: reactive-resume-app-secret
        #       key: OPENID_CLIENT_SECRET
        # - name: OPENID_ISSUER
        #   valueFrom:
        #     secretKeyRef:
        #       name: reactive-resume-app-secret
        #       key: OPENID_ISSUER
        # - name: OPENID_SCOPE
        #   value: "openid profile email"
        # - name: OPENID_TOKEN_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: reactive-resume-app-secret
        #       key: OPENID_TOKEN_URL
        # - name: OPENID_USER_INFO_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: reactive-resume-app-secret
        #       key: OPENID_USER_INFO_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      restartPolicy: Always
      initContainers:
      - name: wait-for-postgres
        image: postgres:16-alpine
        command:
        - /bin/sh
        - -c
        - |
          until pg_isready -h reactive-resume-database -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done
      - name: wait-for-minio
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          until curl -f http://reactive-resume-minio:9000/minio/health/ready; do
            echo "Waiting for minio..."
            sleep 2
          done
