apiVersion: v1
kind: Service
metadata:
  name: reactive-resume-app
  namespace: reactive-resume
spec:
  selector:
    app: reactive-resume-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30300
  type: NodePort