apiVersion: v1
kind: PersistentVolume
metadata:
  name: affine-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /home/k8svolumes/affine/config ## Change to the desired path
    type: DirectoryOrCreate
