apiVersion: v1
kind: PersistentVolume
metadata:
  name: affine-storage-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /home/k8svolumes/affine/storage ## Change to the desired path
    type: DirectoryOrCreate