kind: PersistentVolume
apiVersion: v1
metadata:
  name: immich-library-pv
  namespace: photos-videos
  labels:
    app: immich
spec:
  capacity:
    storage: 100Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/k8svolumes/immich/mounted_storage/library  ## Change to the desired path
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
