apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/k8svolumes/grafana/mounted_storage
  persistentVolumeReclaimPolicy: Retain
