apiVersion: v1
kind: ConfigMap
metadata:
  name: retroarch-config
  namespace: retroarch
data:
  # Environment variables for the container
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/Bucharest"
  # VNC password (change this!)
  VNC_PASSWORD: "retroarch123"