apiVersion: apps/v1
kind: Deployment
metadata:
  name: ots-redis
  namespace: communication
  labels:
    app: ots-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ots-redis
  template:
    metadata:
      labels:
        app: ots-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          command: ["redis-server", "--appendonly", "yes"]
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
