apiVersion: v1
kind: Service
metadata:
  name: go-librespot-web-service
  namespace: home-automation
  labels:
    app: go-librespot-web
spec:
  selector:
    app: go-librespot-web
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30423
    protocol: TCP 