apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingvin-pvc
  namespace: fileshare
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pingvin-pv
