apiVersion: v1
kind: Service
metadata:
  name: pingvin-service
  namespace: fileshare
spec:
  selector:
    app: pingvin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32755
  type: NodePort
