apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-speedtest-tracker
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: speedtest-pv
  hostPath:
    path: /home/k8svolumes/speedtest-tracker/shared_volume/data  ## Change to the desired path
    type: DirectoryOrCreate