apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retroarch-storage
  namespace: retroarch
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
