apiVersion: v1
kind: PersistentVolume
metadata:
  name: kutt-db-pv
  namespace: urlshort
spec:
  capacity:
    storage: 1Gi  # Adjust the size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # You can change this to 'Delete' if needed
  storageClassName: standard  # Ensure this matches your environment's storage class
  hostPath:
    path: /home/k8svolumes/kutt/mounted_storage/db_data_sqlite  # Make sure this path exists and is accessible
