apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: urlshort
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None  # Headless service to allow direct access between Kutt and Redis
