apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-speedtest-tracker
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: speedtest-pv   # ← must match PVC’s storageClassName (or omit both)
  hostPath:
    path: /home/k8svolumes/speedtest-tracker/shared_volume/data   # ← ensure this directory exists on the node