apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker-pvc
  namespace: monitoring
spec:
  storageClassName: speedtest-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
