apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: speedtest-tracker
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
