kind: PersistentVolume
apiVersion: v1
metadata:
  name: immich-library-pv
  namespace: photos-videos
  labels:
    app: immich
spec:
  capacity:
    storage: 100Gi # Adjust the storage size as needed
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/k8svolumes/immich/mounted_storage/library # Local file path
    type: DirectoryOrCreate # Ensures the directory is created if it doesn't exist
  persistentVolumeReclaimPolicy: Retain
