apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-pvc
  namespace: vscode
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
