apiVersion: v1
kind: PersistentVolume
metadata:
  name: vscode-code-server-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
  hostPath:
    path: /home/k8svolumes/vscode/code-server
