apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-code-server-pvc
  namespace: vscode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
