apiVersion: v1
kind: Service
metadata:
  name: postfix
  namespace: smtp
spec:
  selector:
    app: postfix
  ports:
    - protocol: TCP
      port: 25
      targetPort: 25
  type: NodePort  # You can change this to NodePort or LoadBalancer if you need external access
