apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-config
  namespace: smtp
data:
  main.cf: |
    myhostname = smtp.vladsdomain.live
    mydestination = $myhostname, localhost.localdomain, localhost
    mynetworks = 127.0.0.0/8 [::1]/128
    inet_interfaces = all
    smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
    smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    smtpd_use_tls=yes
    smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
    smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
    smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
    mailbox_size_limit = 0
    recipient_delimiter = +
    smtpd_sasl_auth_enable = yes
    broken_sasl_auth_clients = yes
    readme_directory = no
    append_dot_mydomain = no
    biff = no
