apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/k8svolumes/seafile/mounted_volume/seafile