apiVersion: v1
kind: ConfigMap
metadata:
  name: seafile-setup-script
  namespace: seafile
data:
  setup.sh: |
    #!/bin/bash
    set -e
    
    echo "=== Updating Repositories ==="
    apt-get update --fix-missing
    echo "=== I love Nano. Nano ===> VIM"
    apt-get install -y nano --fix-missing
    echo "=== Installing SQLite3 ==="
    apt-get install -y sqlite3 --fix-missing
    sqlite3 --version
    echo "SQLite3 installation completed!"