apiVersion: v1
kind: ConfigMap
metadata:
  name: snapcast-config
  namespace: home-automation
data:
  snapserver.conf: |
    [server]
    threads = -1
    datadir = /var/lib/snapserver
    
    [http]
    enabled = true
    bind_to_address = 0.0.0.0
    port = 1780
    doc_root = /usr/share/snapserver/snapweb
    
    [tcp]
    enabled = true
    bind_to_address = 0.0.0.0
    port = 1704
    
    [stream]
    bind_to_address = 0.0.0.0
    port = 1705
    
    # Audio source - named pipe for Music Assistant
    source = pipe:///tmp/snapfifo/music_assistant?name=MusicAssistant
