apiVersion: v1
kind: Service
metadata:
  name: snapcast-server
  namespace: home-automation
spec:
  selector:
    app: snapcast-server
  ports:
    - name: snapcast
      port: 1704
      targetPort: 1704
      protocol: TCP
    - name: control
      port: 1705
      targetPort: 1705
      protocol: TCP
    - name: http
      port: 1780
      targetPort: 1780
      protocol: TCP
  type: NodePort