apiVersion: v1
kind: PersistentVolume
metadata:
  name: affine-postgres-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /home/k8svolumes/affine/postgress/pgdata
