apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-postgres-pvc
  namespace: note-taking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
