apiVersion: apps/v1
kind: Deployment
metadata:
  name: affine-postgres
  namespace: note-taking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: affine-postgres
  template:
    metadata:
      labels:
        app: affine-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: affine
            - name: POSTGRES_PASSWORD
              value: affinepassword
            - name: POSTGRES_DB
              value: affine
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: affine-postgres-pvc
