apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
data:
  # Base64 encoded values - change these before deploying
  # mysql-root-password: base64 encoded root password
  # mysql-password: base64 encoded wordpress user password
  mysql-root-password: cGFzc3dvcmQxMjM=  # password123
  mysql-password: d29yZHByZXNz          # wordpress