apiVersion: v1
kind: Secret
metadata:
  name: wordpress-mysql-secret
  namespace: wordpress
type: Opaque
data:
  # Base64 encoded MySQL credentials
  mysql-user: d29yZHByZXNz              # wordpress
  mysql-password: d29yZHByZXNz          # wordpress
  mysql-database: d29yZHByZXNz          # wordpress
  mysql-root-password: cGFzc3dvcmQxMjM=  # password123