apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: wordpress
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/k8svolumes/wordpress/mounted_volume/wordpress
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain