apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress
  labels:
    app: wordpress-app
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30180
      protocol: TCP
  selector:
    app: wordpress-app
  type: NodePort