apiVersion: v1
kind: Service
metadata:
  name: glances-latest
  namespace: monitoring
spec:
  selector:
    app: glances-latest
  ports:
    - name: http
      port: 61208
      targetPort: 61208
      nodePort: 30062
  type: NodePort