apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: photos-videos
  labels:
    app: immich-server
spec:
  type: NodePort
  selector:
    app: immich-server
  ports:
    - port: 2283
      targetPort: 2283
      protocol: TCP
      nodePort: 32002
