apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: photos-videos
  labels:
    app: redis-server
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-server
