apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-assistant
  namespace: home-automation
  labels:
    app: music-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-assistant
  template:
    metadata:
      labels:
        app: music-assistant
    spec:
      hostNetwork: true
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: music-assistant
          image: ghcr.io/music-assistant/server:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN", "DAC_READ_SEARCH"]
          volumeMounts:
            - name: music-assistant-data
              mountPath: /data
          env:
            - name: LOG_LEVEL
              value: "info"
      volumes:
        - name: music-assistant-data
          hostPath:
            path: /path/to/your/volume
            type: DirectoryOrCreate
