apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-pvc
  namespace: filebrowser
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: manual
