apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: websocket
      port: 9001
      targetPort: 9001
