apiVersion: v1
kind: PersistentVolume
metadata:
  name: kutt-db-pv
  namespace: urlshort
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: standard
  hostPath:
    path: /home/k8svolumes/kutt/mounted_storage/db_data_sqlite  ## Change to the desired path
    type: DirectoryOrCreate
