apiVersion: v1
kind: PersistentVolume
metadata:
  name: kutt-custom-pv
  namespace: urlshort
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/k8svolumes/kutt/mounted_storage/custom  ## Change to the desired path
    type: DirectoryOrCreate
