apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
  hostPath:
    path: /home/k8svolumes
