apiVersion: apps/v1
kind: Deployment
metadata:
  name: glances
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glances
  template:
    metadata:
      labels:
        app: glances
    spec:
      hostNetwork: true
      containers:
        - name: glances
          image: nicolargo/glances:latest
          command: ["glances", "-w", "--bind", "0.0.0.0", "--port", "61208"]
          ports:
            - containerPort: 61208
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /proc
              name: proc
            - mountPath: /sys
              name: sys
            - mountPath: /etc
              name: etc
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: etc
          hostPath:
            path: /etc
