apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: true
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: home-assistant
          image: "homeassistant/home-assistant:latest"
          volumeMounts:
            - name: home-assistant-config
              mountPath: /config
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - "-c"
                  - "wget -O - https://get.hacs.xyz | bash"
      volumes:
        - name: home-assistant-config
          persistentVolumeClaim:
            claimName: home-assistant-config
