apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/k8svolumes/nextcloud/db_volume"
