apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-app
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-app
  template:
    metadata:
      labels:
        app: nextcloud-app
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:31-apache
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: nextcloud-db
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: MYSQL_USER
          value: nextcloud
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-db-secret
              key: db-password
        - name: NEXTCLOUD_ADMIN_USER
          value: admin
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-db-secret
              key: nextcloud-admin-password
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "localhost *"
        - name: OVERWRITEPROTOCOL
          value: "http"
        - name: OVERWRITECLIURL
          value: "http://localhost"
        - name: REDIS_HOST
          value: nextcloud-redis
        - name: REDIS_HOST_PORT
          value: "6379"
        - name: PHP_MEMORY_LIMIT
          value: "512M"
        - name: PHP_UPLOAD_LIMIT
          value: "512M"
        volumeMounts:
        - name: nextcloud-storage
          mountPath: /var/www/html
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: nextcloud-storage
        persistentVolumeClaim:
          claimName: nextcloud-pvc
