apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: nextcloud
spec:
  selector:
    app: nextcloud-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30588 # You can change this to any port between 30000-32767
  type: NodePort
