apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshwifty
  namespace: sshwifty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshwifty
  template:
    metadata:
      labels:
        app: sshwifty
    spec:
      hostAliases:
        - ip: "192.168.100.50"
          hostnames:
            - "laptop.vladsdomain.live"
      containers:
        - name: sshwifty
          image: niruix/sshwifty:latest
          ports:
            - containerPort: 8182
          env:
            - name: SSHWIFTY_SETTINGS__LISTEN
              value: "0.0.0.0:8182"
            - name: TERM
              value: "xterm-256color"
