apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-pvc
  namespace: seafile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: seafile-pv
