apiVersion: v1
kind: ConfigMap
metadata:
  name: seafile-config
  namespace: seafile
data:
  TIME_ZONE: "UTC"
  SEAFILE_SERVER_HOSTNAME: "seafile.vladsdomain.live"
  SERVICE_URL: "https://seafile.vladsdomain.live"
  # For local access during testing
  NODE_PORT_URL: "http://192.168.100.50:31223"
