apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/k8svolumes/romm/mounted_volume/romm
  persistentVolumeReclaimPolicy: Retain
