apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-mariadb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/k8svolumes/romm/mounted_volume/mariadb ## Change to the desired path
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
