apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-mariadb-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: romm-mariadb-pv
