apiVersion: v1
kind: Service
metadata:
  name: romm
  namespace: romm
  labels:
    app: romm
spec:
  selector:
    app: romm
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31080 # within the default allowed range
  type: NodePort
