apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome
  namespace: selenium
spec:
  selector:
    app: selenium-chrome
  ports:
    - port: 4444
      targetPort: 4444
      nodePort: 30479 # Choose a port between 30000-32767
  type: NodePort
