apiVersion: v1
kind: PersistentVolume
metadata:
  name: pingvin-pv
  namespace: fileshare
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/k8svolumes/pingvinshare/mounted_volume ## Change to the desired path
  persistentVolumeReclaimPolicy: Retain
