apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf
  namespace: pdf
spec:
  selector:
    app: stirling-pdf
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32761
  type: NodePort
